# Ce qu'il faut retenir sur la gestion des erreurs

En C#, lorsqu'il y a **un bug üêû dans notre programme** on appelle √ßa une **exception**. ‚ö†Ô∏è Probl√®me, quand cela se produit l'erreur est "lev√©e" et la pile d'appels est renvoy√©e √† l'utilisateur. De plus, le programme est d√©sormais plant√© et il faudra le red√©marrer pouvoir continuer √† l'utiliser.

Cela pr√©sente plusieurs probl√®mes ‚ö†Ô∏è :

1. SI il y a des exceptions, c'est que notre programme **n'est pas r√©silient**. Il faut trouver un moyen de parer √† toutes les √©ventualit√©s. 
2. Notre programme est inutilisable. Il va falloir le relancer.
3. On risque **d'afficher des informations techniques** √† l'utilisateur : la stacktrace. Mettez vous √† la place de l'utilisateur final. **Il va sans doute pr√©f√©rer avoir un jolie message d'erreur** qu'un charabia technique incompr√©hensible üëÄ. 

# Qu'est ce que la "Stacktrace" ?

Une **pile d'appel**, (ou pile de trace, trace d'appels, etc) √ßa ressemble √† √ßa :

```csharp
Unhandled exception. System.FormatException: Input string was not in a correct format.
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
at System.Int32.Parse(String s)
at MyApp.Calculator.Compute(String[] input) in C:\Users\Sylvain\source\repos\MyApp\Calculator.cs:line 47
at MyApp.SuperCalculator.Compute(String[] input) in C:\Users\Sylvain\source\repos\MyApp\Calculator.cs:line 13
at MyApp.Program.Main(String[] args) in C:\Users\Sylvain\source\repos\MyApp\Program.cs:line 30
```

C'est la liste (la pile plus exactement) de toutes les instructions ex√©cut√©es par le programme qui ont men√© √† l'erreur. **On doit donc la lire de haut en bas de l'instruction la plus r√©cente √† la plus ancienne.**

**La premi√®re ligne √©tant l'erreur lev√©e par le programme en question.**

En g√©n√©ral, lorsqu'on met une application en production (donc pas en test) comme un site internet cod√© en asp .Net Core (le framework web C# de Microsoft) il y a **des configurations par d√©faut qui emp√™chent de montrer la pile d'appels aux utilisateurs finaux. Tr√®s pratique !**

# Comment emp√™cher de divulguer des erreurs aux utilisateurs finaux ?

On va utiliser les blocs try et catch comme dans l'exemple ci dessous :

```csharp
try {
// Mon code.
} catch {
// Si mon code plante,
// ce code va √™tre ex√©cut√©.
}
```

Si je mets un bloc try, je suis oblig√© de mettre un bloc catch. **Si une erreur se produit entre mes accolades try alors le code √† l'int√©rieur du bloc catch va √™tre ex√©cut√©.** 

Evidemment, je ne suis pas oblig√© de mettre une seule ligne de code dans le bloc try. Je peux encapsuler 1000 lignes si √ßa me chante. Mais gare √† la lisibilit√© ! üëÄ

De m√™me que si une erreur se produit dans les m√©thodes appel√©es (et les m√©thodes des m√©thodes) le code √† l'int√©rieur du bloc catch s'ex√©cutera.

Si je le souhaite, je peux **mettre des parenth√®ses √† l'instruction catch pour y passer un objet de type Exception** (ou comme nous allons le rappeler plus bas, les classes d√©riv√©es de la classe exceptions).

```csharp
try {
// Mon code.
} catch (Exception myError) {
// Si mon code plante,
// ce code va √™tre ex√©cut√©.
// et je peux acc√©der √† l'erreur
// grace √† ma variable myError
}
```

L'objet Exception sera **pr√©remplie d'informations sur l'erreur** et elles seront accessibles gr√¢ce √† la variable myError dans cet exemple (comme un param√®tre de fonction). 

**Toutes les exceptions h√©ritent directement ou indirectement de la classe Exception.** Donc, gr√¢ce au polymorphisme, nous pouvons "catcher" des erreurs plus pr√©cises comme par exemple la IndexOutOfRangeException. 

‚ö†Ô∏èMais attention‚ö†Ô∏è : si je mets seulement un catch avec une IndexOutOfRangeException et que j'ai une erreur d'un autre type, l'erreur ne sera pas attrap√©e. 

Si **je choisis de catcher des erreurs bien pr√©cises,** j**e dois tout de m√™me pr√©voir des cas plus g√©n√©ralistes**. Je peux, pour cela, ajouter plusieurs blocs catch.

```csharp
try {
// Mon code.
} catch (IndexOutOfRangeException myError) {
// L'erreur IndexOutOfRangeException
// sera captur√©e √† ce niveau.
}
catch (Exception myError) {
// Toutes les autres erreurs seront captur√©es ici
// parce que la classe Exception
// repr√©sentent l'erreur la plus "g√©n√©rale"
}
```

**L'ordre des blocs est important !** Le code s'ex√©cutant de haut en bas, je dois toujours **mettre en premier (vers le haut) les erreurs les plus sp√©cifiques puis les erreurs les plus g√©n√©riques (vers le bas).** Sinon certaines erreurs ne pourront jamais √™tre "catch√©e" parce qu'une erreur plus vaste les aura captur√© auparavant. **En pratique, le code ne compilera m√™me pas !**

# Et finally dans tout √ßa ?

Je peux ajouter un bloc finally. **Quelle que soit l'erreur d√©clench√©e le bloc finally s'ex√©cutera.** 

```csharp
try {
// Mon code.
}
catch (Exception myError) {
// une erreur
}
finally {
// Cette instruction s'ex√©cutera quelle que soit l'erreur.
}
```

# Et la commande throw ?

De mani√®re simple, la commande throw d√©clenche une erreur. On dit aussi qu'elle permet de lever une exception. C'est √† dire qu'elle affichera par exemple la stracktrace si l'erreur n'est pas attrap√©e. 

Ce qui sous entend que je peux d√©clencher manuellement une erreur si je le souhaite.

```csharp
static void MyAwesomeFunction(){
	throw new NotImplementedException();
}
```

Dans cet exemple, **j'ai voulu √©crire une fonction mais je n'ai pas encore eu le temps de la coder.** Si un ou une coll√®gue de travail essaie d'utiliser ma fonction, il y aura une erreur indiquant que la fonction n'est pas encore impl√©ment√©e. 

J'ai donc "lev√©" manuellement une erreur. Pour cela, j'ai √©cris un throw avec un nouvel objet de type exception, comme ici la "NotImplementedException()" **sans oublier auparavant d'utiliser le mot clef new car il s'agit d'un objet.**

M√™me dans un bloc catch, je peux aussi lever une exception avec la commande throw (si je ne mets rien apr√®s le throw, **c'est l'erreur courante qui sera relanc√©e**). Cela peut avoir un int√©r√™t si je veux quand m√™me remonter l'erreur. 

```csharp
try {
// Mon code.
}
catch (Exception myError) {
// une erreur
throw; // je souhaite tout de m√™me lever l'erreur
}
```

# Et la commande when ?

Je peux aussi r√©cup√©rer une erreur de mani√®re conditionnelle en utilisant l'instruction when. Evidemment, la condition (dans les parenth√®ses du when) doit d√©pendre de l'objet exception captur√©e auparavant.

```csharp
try {
// Mon code.
}
catch (Exception myError) when( myError = ... ){
// une erreur conditionnelle
}
```

# Et en milieu professionnel ?

Voici quelques recommandations sur la gestion des erreurs en milieu professionnel :

- En g√©n√©ral, o**n n'englobe pas la totalit√© du code** par des try et des catch.
- **On encapsule plut√¥t les centres n√©vralgiques** des programmes (appels √† des API, appels √† des BDD, ex√©cution de batch, ou d'op√©ration d'√©criture sur disque, etc).
- C'est une mauvaise pratique de faire un try et un catch **dans le but de masquer une erreur.** Un peu comme si vous laissez la poussi√®re sous le tapis. Vous pouvez faire √ßa si vous "**loggez**" l'erreur dans une base de donn√©e par exemple afin qu'on puisse savoir qu'il y a une erreur √† un endroit pr√©cis.
- **Il est rare d'utiliser plus d'un catch.** Ou alors c'est pour r√©pondre √† un besoin bien sp√©cifique.
- **La commande when est rarement utilis√©e.** (Et je ne savais m√™me pas qu'elle existait avant de r√©aliser ce cours... üò≥).